### PR TITLE
Fixes reverse step and range errors

### PR DESCRIPTION
**Pull request by ccrook**
This fixes two issues.  One is a documentation change - I think I originally had the reverse_step function documented as having value 1.0 before the reference epoch.  This doesn't really make sense, and I changed it a while ago in the format documentation.  This accounts for most of the differences identified in the gie test for the NZGD2000 deformation model.  

The other is that the transformation should fail if the evaluation point or time are outside the range of the deformation model.  In this case the calculated displacement is undefined, not zero. 

Please could you also add an anti-meridian fix on the range tests for the grids and the model.   Actually it is enough just to fix up based on the range of the whole model.  After that it should fit the components by definition.  (I couldn't immediately see where to test if the coordinate system was geographic or projection, so I didn't include this in the patch).

I think with this it will pass the NZGD2000 gie.  Amended model and gie file attached.
[nzgd2000-defmodel.zip](https://github.com/rouault/PROJ/files/4520328/nzgd2000-defmodel.zip)
[nzgd2000-20180701.gie.zip](https://github.com/rouault/PROJ/files/4520331/nzgd2000-20180701.gie.zip)

### CODE REVIEW

**Comment by ccrook** [comment]
@rouault  Also FYI I am building some test grids/cases for antimeridian and polar geocentric.

**Comment by rouault** [comment]
> Please could you also add an anti-meridian fix on the range tests for the grids and the model

You mean that the bbox in the JSON would be specified like [170,south_lat,-175,north_lat] and that should be internally considered as [170,south_lat,185,north_lat] ?

>  Actually it is enough just to fix up based on the range of the whole model. After that it should fit the components by definition

Not sure to have got what you mean

>  (I couldn't immediately see where to test if the coordinate system was geographic or projection, so I didn't include this in the patch).

The implementation only supports geographic.

**Comment by ccrook** [comment]
Sorry - that request wasn't clear - written in haste when I ran out of time yesterday. 

> (I couldn't immediately see where to test if the coordinate system was geographic or projection, so I didn't include this in the patch).
> 
> > The implementation only supports geographic.

That will be why :-)

Ran out of time yesterday, which is why I didn't add the code.  I've pushed the change I was proposing (with a redundant comment about geographic coordinate sys).

I've also added some more appropriate tests for the geocentric methods near the poles and for the longitude wrapping.  The wrapping tests are failing - somewhere I think the longitude values I'm supplying or not considered valid?  I didn't spot where that is.  I'm guessing that will be obvious to you.  As will the most appropriate way of dealing with it (eg not having absurd tests)

The geocentric interpolation/addition tests are passing - as far as I can tell the answers are correct (calculated independently).  It is a far from perfect method, just the best I could come up with to handle near polar deformation grids.  This is an area where a projection could be a useful thing - if anyone wants a polar deformation model!

This is now passing all my NZGD2000 deformation model tests as well - which is brilliant.  And with the wrapping code I don't have to worry how users enter coordinates for Chatham Islands (185/-175)

**Comment by rouault** [comment]
I've fixed the various issues. I've had to remove the wraping test for lon=722 since it exceeds the [-10, 10] radian (so [-571, 571] degree) validity range of generic code at https://github.com/OSGeo/PROJ/blame/master/src/fwd.cpp#L55 . I'm not sure why that range was introduced, probably to avoid people providing accidentally non-geographic coordinates.

Regarding support of projected CRS, for some reason, I had in mind that this was out of scope for this work and more a possibility on the format itself. That said, it could probably be implemented without too big effort, but I'd like some confirmation, to have a clearer idea of the impacts.

- I see the model has 3 CRS fields: source_crs, target_crs and definition_crs. Currently all ignored by PROJ. For the projected case, would all of them be projected, and with the same projection ? (that is same projection method & parameter, but possibly slightly different underlying datums). Or could you have a mix of source_crs/target_crs being geographic and definition_crs projected, or the reverse ?

- if the referencing of the grids could be in a projected CRS, changes in PROJ generic grid code would be needed, because it make quite a few assumptions about grids being referenced to a geographic CRS. Nothing that can't be overcome though.

- if we have the source_crs/target_crs projected, and grids referenced to a geographic CRS (hopefully in the base geographic CRS of the projected CRS, to avoid any datum shift issue...), we'd have to apply the inverse projection each time we want to read in the grid ?

**Comment by ccrook** [comment]
Hi Even

I did think 722 east was a bit unrealistic!

I've added some more words to the specification proposal (in italics below).  The CRS specifications are really only there to provide more complete metadata and/or validation.  I imagine most implementations would already have the coordinate systems defined before they get to use the deformation model.    Possibly having source and definition CRS as potentially different is overcooking it a bit but I could imagine using that at some time in the future.   

- source_crs.  The coordinate reference system to which the deformation model applies
- target_crs.  For a time dependent coordinate transformation the coordinate reference system resulting from applying the deformation.  _It is assumed that the target system is identical to the source system except that its underlying datum differs by the modelled deformation.  If they are projected coordinate systems then they will use the same projection formulae and parameters._
- definition_crs. The coordinate reference system used to define the component spatial models.  _Note that the offset computed defined by the spatial model is in terms of the source_crs.  For example a grid could be defined in a local projection, but it could determine offsets to apply to a geographic coordinate system (for which the direction of east and north might be different).  For the initial version of the format it is required that the definition system is the same as the source coordinate system._

As an example the NZGD2000 model has source NZGD2000 (EPSG:$959), target ITRF96 (EPSG:7907), and definition CRS NZG2000 (which could be EPSG:4959 or EPSG:4167).   

From a calculation point of view I think the only real differences are that 1) geocentric_bilinear interpolation and geocentric addition of east/north offsets are not valid for a projection source/target CRS, longitude wrapping doesn't apply, and possibly different tolerances would apply for EPS. 

I have just realised that one thing I didn't check is strictness of inequalities used in time models.  In particular to implement the Japanese model has components each of which is a step function for one year (implemented by a piecewise function)  So it needs to ensure that only one component will be selected where one ends and the next starts.  I'll build a test case for that soon.

**Comment by ccrook** [comment]
... though I guess in the Japanese case each year is a difference CRS in any case...

**Comment by rouault** [comment]
OK, so to be able to support projected grids / CRS, defmodel.hpp should know if source_crs is projected. Was wondering if a new field in the json was needed. Otherwise EvaluatorIface will need a method to resolve the CRS definition.

**Comment by ccrook** [comment]
I also wondered about putting a field in JSON.  In fact I started adding that and then retracted it when I realised would also have to add the ellipsoid definition (for the lat/lon <-> XYZ functions) to make it independent of the hosting program.  I came to the opinion that information about the CRS was the responsibility of the host.  So that would require a evaluator iface function.  

So I think that the interface just requires a crs_is_geographic function?  How does that sound to you? 

Irrelevant thought follows .. in fact I also realised last night that having a definition CRS was also not hard to add to  defmodel.hpp - it just needs an evaluator interface to convert the coordinates if source and definition CRS are not the same.  Then just use transformated coordinates to evaluate the grids.  Of course  that could end up with an infinite recursion if definition and target CRS are the same and it used an xyzt transformation - maybe that could be restricted to xyz.  However as per above I'm not sure there is a practical requirement for this at the moment, which is why I'm suggesting definition_crs=source_crs initially.

**Comment by rouault** [comment]
> I think that the interface just requires a crs_is_geographic function? How does that sound to you?

yes, was thinking to something along that line

> which is why I'm suggesting definition_crs=source_crs initially.

yes, sounds good to limit to that for now.

**Pull request merged**
