### PR TITLE
Several suggestions

### PR DESCRIPTION
**Pull request by mwtoews**
* Drop third-party `Findnlohmann_json.cmake` in favour of native version installed by the library. There are a number of reasons for this, including that the third-party version does not reliably work on slightly older json.hpp files with different version formats.
* Check MIN_NLOHMANN_JSON_VERSION after `find_package` (which doesn't easily do minimum versions)
* Use `target_compile_definitions` instead of `add_definitions`
* Use `target_link_libraries` instead of `include_directories`, this will propagate other definitions from the library like `-DJSON_DIAGNOSTICS=0 -DJSON_USE_IMPLICIT_CONVERSIONS=1`
* No need to repeat these to test/unit, as they are `PUBLIC` properties

### CODE REVIEW

**Comment by rouault** [comment]
on the linux_gcc_4_8 conf with cmake 3.5 :  "make[2]: *** No rule to make target 'Findnlohmann_json.cmake', needed by 'distdir'.  Stop."

**Comment by mwtoews** [comment]
oh right, I might need another go at these suggestions tomorrow. I'm also reconsidering use of PUBLIC.

**Comment by mwtoews** [comment]
Ok, my suggestions are ready. Take or reject any of these edits you choose, but squash/rebase the commit messages, as they are too detailed.

In the end, I decided to use PRIVATE instead of PUBLIC definitions and target_link_library, as these are only needed internally to build the objects from the header-only library. They don't need to be exported to any dependencies.

Using `target_compile_definitions` instead of `add_definitions` is a bit more explicit (as it needs to be repeated for a few targets), but is the modern CMake way, and I may get around to refactoring the other components later. These targets were identified by searching (via git grep) where `include_nlohmann_json.hpp`/`defmodel.hpp`/`tinshift.hpp` was used.

You may have also seen the [docs for integration with CMake](https://json.nlohmann.me/integration/cmake/).

**Comment by rouault** [comment]
Thanks ! I'll merge this as it, and will squash the OSGeo/PROJ PR

**Pull request merged**
